"""Authoring service — validation, files, draft/publish lifecycle."""

from .files import write_content_file, write_wiki_content_file
from .lifecycle import (
    apply_snapshot_to_published,
    build_lesson_snapshot,
    copy_content_file,
    create_revision_snapshot,
    duplicate_lesson,
    find_lesson_by_slide_id,
    get_working_snapshot,
    persist_draft,
    publish_lesson,
    reorder_slides_in_snapshot,
    rollback_revision,
    slide_exists_in_snapshot,
    snapshot_to_detail,
    update_slide_in_snapshot,
)
from .slide_response import hotspots_from_json, slide_snapshot_to_response, slide_to_response
from .validation import (
    ALLOWED_UPLOAD_TYPES,
    ALLOWED_VERIFY_TYPES,
    MAX_TAG_COUNT,
    MAX_TAG_LENGTH,
    MAX_UPLOAD_BYTES,
    hotspots_to_storage,
    normalize_tag,
    slugify,
    validate_hotspots,
    validate_quiz_questions,
    validate_tags,
    validate_upload,
    validate_verify_type,
    wiki_slugify,
)

__all__ = [
    "ALLOWED_UPLOAD_TYPES",
    "ALLOWED_VERIFY_TYPES",
    "MAX_TAG_COUNT",
    "MAX_TAG_LENGTH",
    "MAX_UPLOAD_BYTES",
    "apply_snapshot_to_published",
    "build_lesson_snapshot",
    "copy_content_file",
    "create_revision_snapshot",
    "duplicate_lesson",
    "find_lesson_by_slide_id",
    "get_working_snapshot",
    "hotspots_from_json",
    "hotspots_to_storage",
    "normalize_tag",
    "persist_draft",
    "publish_lesson",
    "reorder_slides_in_snapshot",
    "rollback_revision",
    "slide_exists_in_snapshot",
    "slide_snapshot_to_response",
    "slide_to_response",
    "slugify",
    "snapshot_to_detail",
    "update_slide_in_snapshot",
    "validate_hotspots",
    "validate_quiz_questions",
    "validate_tags",
    "validate_upload",
    "validate_verify_type",
    "wiki_slugify",
    "write_content_file",
    "write_wiki_content_file",
]
